plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jibunnoji.keyboard'
    compileSdk 35

    defaultConfig {
        applicationId "com.jibunnoji.keyboard"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
}

repositories {
    google()
    mavenCentral()
}
